// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Sg2IunpFoyKO2S15ZpfAZnXXD3EjX2I',
    appId: '1:515462066924:web:eba2d6d428fd563d9eebc9',
    messagingSenderId: '515462066924',
    projectId: 'portfolio-fd102',
    authDomain: 'portfolio-fd102.firebaseapp.com',
    storageBucket: 'portfolio-fd102.firebasestorage.app',
    measurementId: 'G-Z7X70RR6JZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6oL9nED9asxw9_HQouvIwEFljflkDmUA',
    appId: '1:515462066924:ios:fd9bef7f71cf0b7f9eebc9',
    messagingSenderId: '515462066924',
    projectId: 'portfolio-fd102',
    storageBucket: 'portfolio-fd102.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6oL9nED9asxw9_HQouvIwEFljflkDmUA',
    appId: '1:515462066924:ios:fd9bef7f71cf0b7f9eebc9',
    messagingSenderId: '515462066924',
    projectId: 'portfolio-fd102',
    storageBucket: 'portfolio-fd102.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Sg2IunpFoyKO2S15ZpfAZnXXD3EjX2I',
    appId: '1:515462066924:web:18c8bced3a55c4729eebc9',
    messagingSenderId: '515462066924',
    projectId: 'portfolio-fd102',
    authDomain: 'portfolio-fd102.firebaseapp.com',
    storageBucket: 'portfolio-fd102.firebasestorage.app',
    measurementId: 'G-V0LKJKPDS7',
  );
}
